freebsd_instance:
  image: freebsd-11-2-release-amd64

task:
  name: FreeBSD 11.2
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock || echo ""
  # Install Rust
  setup_script:
    - pkg install -y pkgconf fusefs-libs
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y
  build_script:
    - . $HOME/.cargo/env
    - cargo build --all --all-targets
  test_script:
    - . $HOME/.cargo/env
    - cargo test --all
  doc_script:
    - . $HOME/.cargo/env
    - cargo doc --all --no-deps
  before_cache_script: rm -rf $CARGO_HOME/registry/index
