language: rust
rust: stable
jobs:
  include:
    - os: linux
      dist: bionic
      env: FEATURES=
      install: sudo apt-get update && sudo apt-get install -y libfuse-dev
    - os: linux
      dist: bionic
      env: FEATURES=abi-7-19
      install: sudo apt-get update && sudo apt-get install -y libfuse-dev
#    - os: linux
#      dist: focal
#      env: FEATURES=abi-7-21
#      install: sudo apt-get update && sudo apt-get install -y libfuse3-dev fuse3
script:
  - cargo build --all --all-targets --features=$FEATURES
  - cargo build --all --all-targets --no-default-features
  - cargo test --all --features=$FEATURES
  - cargo doc --all --no-deps --features=$FEATURES
