[package]
name = "fuser"
edition = "2018"
version = "0.4.0"
authors = ["Christopher Berner <christopherberner@gmail.com>"]
description = "Filesystem in Userspace (FUSE) for Rust"
documentation = "https://docs.rs/fuser"
homepage = "https://github.com/cberner/fuser"
repository = "https://github.com/cberner/fuser"
readme = "README.md"
keywords = ["fuse", "filesystem", "system", "bindings"]
categories = ["external-ffi-bindings", "api-bindings", "filesystem", "os::unix-apis"]
build = "build.rs"
license = "MIT"

[badges]
travis-ci = { repository = "cberner/fuser" }

[dependencies]
libc = "0.2.51"
log = "0.4.6"
thread-scoped = "1.0.2"

[dev-dependencies]
env_logger = "0.7"
clap = "2.32"
bincode = "1.3.1"
serde = {version = "1.0.102", features=["std", "derive"]}

[build-dependencies]
pkg-config = "0.3.14"

[features]
abi-7-9 = []
abi-7-10 = ["abi-7-9"]
abi-7-11 = ["abi-7-10"]
abi-7-12 = ["abi-7-11"]
abi-7-13 = ["abi-7-12"]
abi-7-14 = ["abi-7-13"]
abi-7-15 = ["abi-7-14"]
abi-7-16 = ["abi-7-15"]
abi-7-17 = ["abi-7-16"]
abi-7-18 = ["abi-7-17"]
abi-7-19 = ["abi-7-18"]
