[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuser = { path = "../../" }
libc = "0.2.51"
env_logger = "0.9"
clap = { version = "3.0", features = ["cargo"] }
