[package]
name = "null"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "null"
path = "src/null.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuser = { path = "../../."}
log = "0"
env_logger = "0"
